FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt requirements-dev.txt ./
RUN python3.12 -m pip install --upgrade pip \
    && python3.12 -m pip install -r requirements.txt -r requirements-dev.txt

COPY . /app
ENTRYPOINT ["python3.12", "-m"]
CMD ["src.train.record_video"]
