FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt requirements-dev.txt ./
RUN python3 -m pip install --upgrade pip \
    && pip install -r requirements.txt -r requirements-dev.txt

COPY . /app
CMD ["python3", "-m", "src.train.train_dqn"]
